"""add shipping fee and payout split

Revision ID: 301aad38fa30
Revises: 69012c2ef609
Create Date: 2026-08-06 17:39:40.432298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '301aad38fa30'
down_revision: Union[str, Sequence[str], None] = '69012c2ef609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipping_base_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('shipping_per_km_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(
        'merchants',
        sa.Column('commission_rate', sa.Numeric(precision=5, scale=4), nullable=False, server_default='0.10'),
    )
    op.add_column(
        'orders',
        sa.Column('shipping_fee', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'),
    )
    op.add_column(
        'orders',
        sa.Column('commission_rate', sa.Numeric(precision=5, scale=4), nullable=False, server_default='0'),
    )
    op.add_column(
        'orders',
        sa.Column('merchant_payout', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'),
    )
    op.add_column(
        'orders',
        sa.Column('shipper_payout', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'),
    )
    # Orders placed before this migration had no shipping fee and the merchant
    # received the full subtotal (100%, i.e. no commission and no shipper cut) —
    # backfill merchant_payout to reflect that historical reality rather than
    # leaving it at 0, which would make old completed orders look like the
    # merchant was never paid.
    op.execute("UPDATE orders SET merchant_payout = subtotal")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'shipper_payout')
    op.drop_column('orders', 'merchant_payout')
    op.drop_column('orders', 'commission_rate')
    op.drop_column('orders', 'shipping_fee')
    op.drop_column('merchants', 'commission_rate')
    op.drop_table('platform_settings')
    # ### end Alembic commands ###
