"""add merchant rating and merchant rating on orders

Revision ID: 4c0e27d3667d
Revises: 301aad38fa30
Create Date: 2026-08-06 18:16:57.622260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c0e27d3667d'
down_revision: Union[str, Sequence[str], None] = '301aad38fa30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'merchants',
        sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=False, server_default='5.00'),
    )
    # merchant_id has no sensible constant default (it's a real FK, not a
    # flag) — add nullable, backfill from the rating's own order, then
    # tighten to NOT NULL. Existing rating rows always have an order_id, so
    # this backfill is exhaustive.
    op.add_column('ratings', sa.Column('merchant_id', sa.UUID(), nullable=True))
    op.add_column('ratings', sa.Column('merchant_score', sa.SmallInteger(), nullable=True))
    op.add_column('ratings', sa.Column('merchant_comment', sa.Text(), nullable=True))
    op.execute(
        "UPDATE ratings SET merchant_id = orders.merchant_id "
        "FROM orders WHERE orders.id = ratings.order_id"
    )
    op.alter_column('ratings', 'merchant_id', nullable=False)
    op.create_index(op.f('ix_ratings_merchant_id'), 'ratings', ['merchant_id'], unique=False)
    op.create_foreign_key(None, 'ratings', 'merchants', ['merchant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.drop_index(op.f('ix_ratings_merchant_id'), table_name='ratings')
    op.drop_column('ratings', 'merchant_comment')
    op.drop_column('ratings', 'merchant_score')
    op.drop_column('ratings', 'merchant_id')
    op.drop_column('merchants', 'rating')
    # ### end Alembic commands ###
